services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=perps_user
      - POSTGRES_PASSWORD=mysecretpasswordfordb
      - POSTGRES_DB=perps_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: perps_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  minio:
    image: minio/minio:latest
    container_name: perps_minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=fake-local-key
      - MINIO_ROOT_PASSWORD=fake-local-secret
    volumes:
      - miniodata:/data
    command: server /data --console-address ":9001"

volumes:
  db_data:
  redisdata:
  miniodata:
